[[main]]
  name = "Blog"
  identifier = "blog"
  weight = 10
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>' 
[[main]]
  name = "Documentation"
  identifier = "documentation"
  weight = 50
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
[[main]]
  name = "Manuel d'utilisation"
  identifier = "manuel"
  parent = "documentation"
  url = "https://docs.darktable.org/usermanual/stable/fr/"
  weight = 1  
